version: '3'

services:
  tasklogs:
    build: ./taskLogs
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  taskmanager:
    build: ./taskManager
    ports:
      - "8001:8001"
    depends_on:
      - mongo

  postgres:
    image: postgres
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"

  mongo:
    image: mongo
    ports:
      - "27017:27017"
