version: '3'

networks:
  work-network:

services:
  postgres:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ./data:/data/db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    networks:
      - work-network

  mongo:
    image: mongo
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    networks:
      - work-network

  taskmanager:
    build: ./taskManager
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    networks:
      - work-network

  tasklogs:
    build: ./taskLogs
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    networks:
      - work-network